version: "3.8"
services:
    web:
        build: .
        ports:
            - "1234:1234"
        volumes:
            - ./src:/app/src  # Mount the local src directory to the /app/src in the container
            - ./dist:/app/dist  # Optional: Mount dist if you want to see build results on host
        environment:
            - NODE_ENV=development
