name: Build and Deploy to GitHub Pages

# Defines when the workflow should run. Triggers on pushes and pull requests to the main branch.
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

# Defines the jobs to run in this workflow.
jobs:
    build-and-deploy:
        # Specifies the type of runner that the job will run on.
        runs-on: ubuntu-latest

        steps:
        # Step to checkout the repository so the workflow can access it.
        - name: Checkout code
          uses: actions/checkout@v2

        # Sets up a specific version of Node.js to ensure compatibility with the project's dependencies.
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
              node-version: '16'  # This version should be compatible with all dependencies.

        # Clears Yarn cache to prevent any cached dependencies from affecting new installations.
        - name: Clear Yarn cache
          run: yarn cache clean

        # Installs dependencies ensuring any updates are forced, ignoring potential lock files.
        - name: Install dependencies
          run: yarn install --force

        # Outputs the version of Parcel being used to help diagnose version-related issues.
        - name: Check Parcel version
          run: npx parcel --version

        # Builds the project using Parcel; configured to output the build to the 'dist' directory.
        - name: Build
          run: yarn build

        # Deploys the content of the 'dist' directory to the 'gh-pages' branch, utilizing a GitHub token for authentication.
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@4.1.4
          with:
              branch: gh-pages
              folder: dist
              token: ${{ secrets.GITHUB_TOKEN }}
