name: Deploy to GitHub Pages # Name of the workflow

on: # Specifies the event(s) that triggers the workflow
  push:
    branches:
      - main # Trigger the workflow on a push to the master branch

jobs: # Jobs to be executed. These run in parallel by default.
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the type of virtual host machine to run the job on

    steps: # Steps represent a sequence of tasks to be performed
      - name: Checkout Code # Human-readable name for this step
        uses: actions/checkout@v2 # Uses a pre-built action to check out the repository code

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Set the Node.js version

      - name: Install Dependencies
        run: yarn install # Runs a command to install dependencies

      - name: Build the Project
        run: yarn build # Command to build your project

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch to deploy to
          folder: dist # The directory to deploy from
          token: ${{ secrets.GITHUB_TOKEN }} # Uses a built-in GitHub token for authentication
